Move validation
sadmadrus/chessBox pull request #16
Opened 2023-02-10 10:37 UTC by loskutovanl

[WIP] validation

validaiton.md - описание работы сервиса

move-validation.go - общая логика валидации широкими мазками. Код еще не готов. Буду добавлять комментарии по мере продвижения.

Создают PR, чтобы наглядно получать комментарии построчно.

2023-02-10 11:36 UTC, nekr0z requested changes

2023-02-10 11:36 UTC, nekr0z commented on VALIDATION.md
> +* фигура piece
Давайте зафиксируем сразу форматы, как зафиксировали для доски.
Фигура piece — это  в каком формате? Одна буква? k/q/r/b/n/p? Вам же цвет не нужен…

2023-02-10 11:36 UTC, nekr0z commented on VALIDATION.md
> +* начальная клетка предполагаемого хода from
И для клеток предлагаю тоже зафиксировать формат. Буквацифра? Номер? Что-то другое?

2023-02-10 11:36 UTC, nekr0z commented on VALIDATION.md
> +* Body: JSON конечная доска board в форате FEN
FEN?
или UsFEN, раз принимать решили его?
тут не URL, тут можно и FEN, конечно...

2023-02-10 11:48 UTC, nekr0z commented
Может, убрать файл с зачатками кода из реквеста? Тогда спецификацию готовую можно будет уже смержить…

2023-02-12 07:12 UTC, loskutovanl commented on VALIDATION.md
> +* начальная клетка предполагаемого хода from
наверное, имеет смысл чтобы валидатор был универсальным и работал с любой полученной фигурой и любым представлением клетки. Добавила и номер и буквуцифру

2023-02-12 07:16 UTC, loskutovanl commented on VALIDATION.md
> +* Body: JSON конечная доска board в форате FEN
если в дальнейшем это будет снова передаваться в url, логично сделать UsFen. Изменила

2023-02-12 07:17 UTC, loskutovanl commented on VALIDATION.md
> +* фигура piece
Чтобы мог просто взять фигуру на клетке и не заморачиваться кому на принадлежит, добавила оба цвета

2023-02-12 12:13 UTC, nekr0z reviewed
Опечатку в предпоследней строке я исправил.

Кроме одного комментария (я не настаиваю, просто кажется логичным) — LGTM.

2023-02-12 12:13 UTC, nekr0z commented on VALIDATION.md
> +* новая фигура newpiece, в которую нужно превратить пешку при достижении последнего ряда (k/q/r/b/n/K/Q/R/B/N)
Здесь просится ремарка «необязательный параметр».

2023-02-13 07:51 UTC, loskutovanl commented on VALIDATION.md
> +* новая фигура newpiece, в которую нужно превратить пешку при достижении последнего ряда (k/q/r/b/n/K/Q/R/B/N)
добавила

2023-02-13 08:06 UTC, nekr0z approved these changes
LGTM

2023-02-13 08:09 UTC, merged