added simple validation (lines 1-235)
sadmadrus/chessBox pull request #27
Opened 2023-02-12 09:55 UTC by loskutovanl

[WIP] simple validation
добавлена простая валидация движения фигуры (строки 1-235). - # 1 из [https://github.com/sadmadrus/chessBox/blob/move-validation/VALIDATION.md](VALIDATION.md )

Принимаю пожелания по улучшею читаемости и логики и ошибкам.

Вопрос, что делать с логами, если у нас для них отдельный сервис?

2023-02-12 10:01 UTC, sadmadrus commented
> 

Пока нет описания сервиса, можно подготовить функцию запроса к сервису и подождать немного

2023-02-12 12:11 UTC, sadmadrus commented on move-validation.go
> +	// 2. Если фигура в endCell принадлежит самому участнику o, ход невозможен.
тут похоже опечатка или слово не дописано

2023-02-12 12:46 UTC, nekr0z requested changes
Надо смерджить dev сюда, и сделать, чтобы проходились автопроверки; тогда будем тесты добавлять и логику оттачивать.

2023-02-12 12:46 UTC, nekr0z commented on move-validation.go
> +package chessBox
Тогда пусть это будет package validation, и пусть он живёт в /validation (или в /pkg/validation — если мы собираемся пользоваться /pkg, хотя я не вижу в этом нужды, у нас же весь проект на Go), или даже в /internal/validation пока — но, поскольку это самостоятельный сервис, наверно, прятать его в internal незачем ;)
Короче, он точно не должен быть в основном пакете и в корневой директории :)

2023-02-12 12:46 UTC, nekr0z commented on move-validation.go
> +	log "github.com/sirupsen/logrus"
Забыла сделать go get для этого модуля, и он не добавился в go.mod?

2023-02-12 12:46 UTC, nekr0z commented on move-validation.go
> +		case WhitePawn, BlackPawn:
Если тут имеются в виду константы из internal/board, то можно смёржить dev в эту ветку, импортировать пакет (import github.com/sadmadrus/chessBox/internal/board), и ссылаться как board.WhitePawn (тип board.Piece в итоге оказался публичным, так что им можно пользоваться в полный рост).

2023-02-12 12:46 UTC, nekr0z commented on move-validation.go
> +		from := Sq(fromParsed)
board.Sq ?

2023-02-12 12:46 UTC, nekr0z commented on move-validation.go
> +			log.Errorf("%w: %v (from)", errSquareNotExist, fromParsed)
errSquareNotExist — неэкспортированная переменная типа error из пакета board. Надо или там её экспортировать или в этом пакете сделать свою переменную для этой ошибки.

А правильно будет не делать ни того, ни другого, и просто `fmt.Sprintf("ошибка при указании клетки: %s", fromParsed)` — ведь это идёт только в лог, ты никуда эту ошибку не прокидываешь, а в лог всё равно идёт строка, а не error, поэтому без разницы, можно ли его Unwrap() во что бы то ни было внятное — главное, чтобы человекочитаемо было.

2023-02-12 12:46 UTC, nekr0z commented on move-validation.go
> +		from := Sq(fromParsed)
И да, если это board.Sq, то цифры не обработаются.
board.Sq() цифры принимает как int, а `toParsed` — string, даже если содержимое из цифр.

2023-02-12 12:46 UTC, nekr0z commented on move-validation.go
> +		default: // если число piece не целое (можно вынести выше в валидацию входных данных)
Если `piece` типа `board.Piece`, то это в любом случае int ;-)

2023-02-12 12:46 UTC, nekr0z commented on move-validation.go
> +}
Это всё пока надо сделать stub-ами, т.е. функциями, которые не работают, но не мешают остальному коду компилироваться — добавить в каждую `return nil`, например, и подписать, что TODO.

2023-02-13 08:14 UTC, da070116 commented on move-validation.go
> +	isFigureRightColor := checkFigureColor(figure)
насколько не в Golang-стиле использовать метод самой фигуры? типа `if currentTurnSide == figure.GetColor()`

2023-02-13 08:17 UTC, nekr0z commented on move-validation.go
> +	isFigureRightColor := checkFigureColor(figure)
Вполне идиоматично — если у фигуры есть этот метод.

2023-02-13 08:18 UTC, da070116 commented on move-validation.go
> +func MovePawn(piece int, fromRow, fromColumn, toRow, toColumn float64) error {
много волшебных цифр, не очень понятная для чтения функция

2023-02-13 08:48 UTC, loskutovanl commented on move-validation.go
> +	// 2. Если фигура в endCell принадлежит самому участнику o, ход невозможен.
поправила

2023-02-13 08:49 UTC, loskutovanl commented on move-validation.go
> +package chessBox
добавила пакет

2023-02-13 08:49 UTC, loskutovanl commented on move-validation.go
> +	log "github.com/sirupsen/logrus"
обновила

2023-02-13 08:49 UTC, loskutovanl commented on move-validation.go
> +		case WhitePawn, BlackPawn:
Да, на момент выкатки еще не было все слито в dev. Сейчас оно есть, затянула и обновила ссылки

2023-02-13 09:57 UTC, nekr0z commented on validation/move-validation.go
> +	newBoard := b.GenerateBoardAfterMove(from, to) // TODO написать функцию
Добавить новый метод к типу, который объявлен в другом пакете, не получится (ну, то есть это надо делать в том пакете тогда).
Фактически, здесь надо создать копию b, и на этой копии вызвать метод b.Move(from, to).

2023-02-13 10:00 UTC, nekr0z commented on validation/move-validation.go
> +	// "github.com/sadmadrus/chessBox/internal/board"
Импорты надо привести в порядок: не везде досконально следуют Uber Go Style Guide (хотя вообще в сообществе его очень уважают), но конкретно [пункт про импорты](https://github.com/uber-go/guide/blob/master/style.md#import-group-ordering) настолько широко считается правильной практикой, что удивительно, как это ещё в `go fmt` не добавили.

2023-02-13 10:03 UTC, loskutovanl commented on move-validation.go
> +func MovePawn(piece int, fromRow, fromColumn, toRow, toColumn float64) error {
Мне тоже кажется что не очень непонятно может быть, подумаю как лучше сделать

2023-02-13 10:03 UTC, nekr0z commented on validation/move-validation.go
> +	figure := b.GetFigure(from) // TODO описать функцию
Если имеется в виду, что `figure` типа board.Piece, то `figure, err := b.Get(from)`

2023-02-13 13:57 UTC, sadmadrus commented on move-validation.go
> +func MovePawn(piece int, fromRow, fromColumn, toRow, toColumn float64) error {
можно попробовать все утолкать в структуру с набором полей

2023-02-15 20:06 UTC, nekr0z commented on validation/move-validation.go
> +func MovePawn(piece board.Piece, from, to square) error {
Все эти функции `MoveXXX(piece board.Piece, from, to square) error {}` экспортированы — а зачем?

Вне пакета `validation` воспользоваться ими невозможно, потому что ни сам тип `square`, ни его конструктор `newSquare()` не экспортированы — так может, сделать их локальными?
Особенно с учётом того, что пакет, фактически, описывает отдельный микросервис — есть ли смысл экспортировать из него что-то, кроме хендлеров? Или мы планируем этой логикой ещё в каком-то месте системы пользоваться?

2023-02-15 20:08 UTC, nekr0z commented on validation/move-validation.go
> +func SimpleValidation(w http.ResponseWriter, r *http.Request) {
«Снаружи» эта функция будет вызываться как `validation.SimpleValidation` — громоздко же. `validation.Simple` вполне хватило бы, КМК.

2023-02-15 20:17 UTC, nekr0z commented on validation/move-validation.go
> +	column float64
Это не столько замечание, сколько искреннее любопытство: а зачем `float64`?

2023-02-16 08:45 UTC, sadmadrus commented on validation/move-validation.go
> +	newBoard := b.GenerateBoardAfterMove(from, to) // TODO написать функцию
а мы же можем описать интерфейс на базе того типа и расширить его своим методом?

2023-02-16 09:00 UTC, nekr0z commented on validation/move-validation.go
> +	newBoard := b.GenerateBoardAfterMove(from, to) // TODO написать функцию
Можем, но конкретно для этого случая это может оказаться стрельбой из пушки по воробьям.

2023-02-16 18:31 UTC, loskutovanl commented on move-validation.go
> +		from := Sq(fromParsed)
да, я исправила, чтобы и цифры и буквенно-цифровые значения обработались

2023-02-16 18:32 UTC, loskutovanl commented on move-validation.go
> +			log.Errorf("%w: %v (from)", errSquareNotExist, fromParsed)
исправила

2023-02-16 18:32 UTC, nekr0z commented
Линтер по делу ругается: все его рекомендации стоит воплотить — это повысит читаемость кода ;)

2023-02-16 18:33 UTC, loskutovanl commented on move-validation.go
> +		default: // если число piece не целое (можно вынести выше в валидацию входных данных)
теперь при валидации piece проверяется корректно, default точно не нужен, удалила

2023-02-16 18:33 UTC, loskutovanl commented on move-validation.go
> +}
done and done

2023-02-16 18:34 UTC, loskutovanl commented on move-validation.go
> +func MovePawn(piece int, fromRow, fromColumn, toRow, toColumn float64) error {
переделала со структурой square, мне кажется стало понятнее

2023-02-16 18:34 UTC, loskutovanl commented on validation/move-validation.go
> +	newBoard := b.GenerateBoardAfterMove(from, to) // TODO написать функцию
использую b.Get

2023-02-16 18:35 UTC, loskutovanl commented on validation/move-validation.go
> +	// "github.com/sadmadrus/chessBox/internal/board"
done

2023-02-16 18:35 UTC, loskutovanl commented on validation/move-validation.go
> +func MovePawn(piece board.Piece, from, to square) error {
думаю, не планируем. сделала не экспортируемые

2023-02-16 18:35 UTC, loskutovanl commented on validation/move-validation.go
> +func SimpleValidation(w http.ResponseWriter, r *http.Request) {
соглашусь

2023-02-16 18:37 UTC, loskutovanl commented on validation/move-validation.go
> +	column float64
мне приходится брать модули в методах, а math.Abs определен для float64

2023-02-16 18:47 UTC, nekr0z commented on validation/move-validation.go
> +	column float64
Ну слууууушай! Вот тебе abs для интов, можешь пользоваться:
```
func abs(n int) int {
    if n < 0 { return -n }
    return n
}
```
60 байт вместе с сигнатурой :) А у тебя каждое поле структуры на 8 байт раздуто, и ты к ней обращаешься постоянно…

2023-02-16 18:52 UTC, nekr0z commented
Упс, в тесте старое имя функции. Я как раз полез править, а ты уже смёржила :)

2023-02-17 11:01 UTC, loskutovanl commented on validation/move-validation.go
> +	column float64
не подумала про память, исправила

2023-02-17 11:02 UTC, loskutovanl commented
Немного реорганизовала структуру для удобства и переименовала файлы. Добавила тесты для всех фигур. В процессе нашла баг для движения пешек и исправила его.

2023-02-17 11:56 UTC, sadmadrus commented on move-validation.go
> +var (
не замечание, а скорее вопрос: не красивее ли смотрелась бы структура ошибок, вместо кучи переменных?

2023-02-17 14:30 UTC, loskutovanl commented on move-validation.go
> +var (
Ну я в одной книге читала что так объявляют, сложилось впечатление что это идиоматично.

Или нет?

2023-02-17 15:02 UTC, nekr0z commented on validation/moves.go
> +// square клетка доски, моделирует ряд row и колонку column на шахматной доске в форматах float64
Уже не float64 :)

2023-02-17 15:02 UTC, nekr0z commented on validation/controllers.go
> +// пакет validation валидирует ходы по текущему состоянию доски, начальной и конечной клеткам, и фигуре
Точку зря убрала. По правилам хорошего тона godoc, описания пакетов, типов и функций — законченные предложения; начинаются с заглавной буквы (исключение — неэкспортированные типы и функции), заканчиваются точкой. :)

2023-02-17 15:02 UTC, nekr0z commented on validation/controllers.go
А `logrus` точно нужен? Я понимаю, что он гибкий, удобный и модный, но ты ведь пока не делаешь ничего такого, для чего бы не хватило пакета `log` стандартной библиотеки…

В Go есть хорошая традиция минимализма в зависимостях, вплоть до того, что, если тебе нужна только одна функция из пакета, считается вполне кошерным эту функцию оттуда скопипастить, а не тянуть в зависимости пакет целиком…

2023-02-17 15:02 UTC, sadmadrus commented on move-validation.go
> +var (
не знаю. Просто в том же респонсе коды ответа лежат в структуре - показалось, что так удобнее с ними работать

2023-02-17 15:09 UTC, nekr0z commented on move-validation.go
> +var (
Вот чего в Go нет (и остро не хватает, по-моему), так это идиоматичной работы с ошибками :)
Так тоже объявляют.

Хотя, например, Dave Cheney вообще считает, что даже в стандартной библиотеке [сделано не по-людски](https://dave.cheney.net/2016/04/07/constant-errors). Во многом он прав, и очень интересные мысли у него ещё по ссылке, которой заканчивается этот текст…

Мы как-то привыкли забывать, что `error` — это не тип, а интерфейс.

2023-02-21 17:39 UTC, loskutovanl commented on validation/controllers.go
> +// пакет validation валидирует ходы по текущему состоянию доски, начальной и конечной клеткам, и фигуре
Исправила

2023-02-22 08:59 UTC, loskutovanl commented
Небольшие правки в Simple и спецификации после юнит тестов.


Блок Advanced и ниже смотреть ещё рано. Не готово.
Частично начала делать из-за спонтанно возникшего свободного времени.

2023-02-24 18:09 UTC, loskutovanl commented on validation/controllers.go
Поменяла logrus на log

2023-02-24 19:45 UTC, loskutovanl commented
В блоке Simple готов сервис и методы движения фигур для его обработки. Добавлены тесты на все функции и юнит-тесты.
Не вижу открытых критичных вопросов по simple, поэтому предлагаю смержить ветку.


p.s. в активном процессе работа над advanced, но поскольку это уже другое направление, то для ее ревью я лучше создам отдельный PR. Пока что ничего, связанного с advanced, смотреть и проверять не нужно, оно еще не готово.

2023-02-25 07:56 UTC, loskutovanl commented
Оставила только куски по Simple в ветке. Готовы к слиянию!

2023-02-25 07:57 UTC, merged