Advanced validation
sadmadrus/chessBox pull request #33
Opened 2023-03-06 11:27 UTC by loskutovanl

Сделала валидацию advanced - сервис #2 из [validation.md](https://github.com/sadmadrus/chessBox/blob/advanced-validation/validation/VALIDATION.md)

Написала тесты ко всем функциям, добавила юнит тесты и Fuzz тесты. `go test -fuzz FuzzAdvanced .`  на время еще не запускала.

Налетайте...

Пока делала, поняла, что мы нигде не валидируем саму доску (например, доска с 2 королями, доска без королей и т.п.). Возник вопрос нужно ли это где-то делать вообще?

2023-03-06 11:33 UTC, sadmadrus commented
Доску, по-идее, гененрирует сервис игровой сессии. А вот нужна валидация доски потом - нужно подумать

2023-03-06 15:47 UTC, nekr0z commented
Насчёт валидации доски — это надо написать; я могу заняться.

2023-03-07 17:31 UTC, sadmadrus commented
> Насчёт валидации доски — это надо написать; я могу заняться.

Если никто не против, то давай

2023-03-07 17:41 UTC, nekr0z commented
> > Насчёт валидации доски — это надо написать; я могу заняться.
> 
> Если никто не против, то давай

#34 — сделаю, рассчитываю до конца недели, если без форс-мажоров.

2023-03-08 12:09 UTC, nekr0z reviewed
В общем и целом LGTM; несколько замечаний написал :)

2023-03-08 12:09 UTC, nekr0z commented on validation/parse.go
> +func parseNewpiece(newpiece string) (board.Piece, error) {
Мне не нравится нарушение принципа DRY здесь. Почему не использовать уже написанную parsePiece(), которая отрабатывает ту же самую логику, а отдельно обработать только те случаи, которые отличаются?

2023-03-08 12:09 UTC, nekr0z commented on validation/controllers_test.go
> +	"github.com/sadmadrus/chessBox/internal/board"
Это должно быть во второй секции импортов, не стандартная библиотека же.

2023-03-08 12:09 UTC, nekr0z commented on validation/moves.go
> +	return int8(s1.row*8 + s1.column)
DRY!!!
```go
return int8(s1.toInt)
```
Иначе потом рефакторинг будет очень муторным занятием.

2023-03-08 12:09 UTC, nekr0z commented on validation/moves.go
> +	return false
А почему не просто
```go
return s1.toInt == s2.toInt
```
?

2023-03-08 12:09 UTC, nekr0z commented on validation/controllers_test.go
> +			t.Fatalf("unexpected reply: %s", res.Status)
Надо ещё проверить ответы на HEAD.

И по спеке на GET в теле ответа содержится новая доска — это тоже можно проверить в этом тесте. Понятно, в fuzz'е не проверить правильность, но само наличие — можно и нужно.

2023-03-08 12:09 UTC, nekr0z commented on validation/advancedLogic.go
> +// разрешена (король и ладья еще не двигались, между ними все клетки пустые). НО: Поле, на котором королль оказывается
Опечатка: «королль».

2023-03-08 12:09 UTC, nekr0z commented on validation/advancedLogic.go
> +	}
А зачем нужен вот этот отдельный кусок логики? Можно было просто добавить короля в проверку шаха (да, технически «шах королём» невозможен, но смысл-то тот же, а код это бы упростило значительно, насколько я могу судить).

2023-03-08 12:09 UTC, nekr0z commented on validation/advancedLogic.go
> +	}
А здесь — хотя бы теоретически — ошибка возможна? Поправьте меня, если я ошибаюсь, но у меня сложилось впечатление, что если предыдущее действие ошибки не вызвало, то вот тут ошибка может возникнуть только в том случае, если одна из этих функций (`getSquareByPiece()` или `isSquareChecked`) написана некорректно.

А если так, то появление _любой_ ошибки в этом месте — признак серьёзного косяка в коде. И надо не выпихивать `errSquareNotExists` вверх по стеку (и — в итоге — пользователю по HTTP), а возвращать в этом месте новую серьёзную ошибку; настолько серьёзную, что сервис в целом на этом месте пользователю будет выдавать «Internal Server Error».

Обработка ошибкок должна быть _обработкой_ ошибок.

2023-03-09 08:18 UTC, loskutovanl commented
> В общем и целом LGTM; несколько замечаний написал :)

Спасибо за обратную связь, хоть кто-то всё прочитал 😄

Буду править потихоньку, по наличию свободного времени, отпишусь когда всё

2023-03-09 08:19 UTC, loskutovanl commented on validation/advancedLogic.go
> +	}
Думала, что у каждой функции должен быть единый смысловой кусок.
То есть если объединить, получится немного как солянка, которая и шахи проверяет и близость королей

2023-03-09 09:33 UTC, nekr0z commented on validation/advancedLogic.go
> +	}
Просто близость королей — в алгоритмическом смысле — это шах королём. То есть можно воспользоваться той же логикой, которая уже написана, и не писать отдельную...

2023-03-09 11:03 UTC, loskutovanl commented on validation/moves.go
> +	return false
потому что люблю усложнять)
исправила

2023-03-09 11:24 UTC, loskutovanl commented on validation/parse.go
> +func parseNewpiece(newpiece string) (board.Piece, error) {
соглашусь. перенесла всё в parsePiece

2023-03-09 11:57 UTC, loskutovanl commented on validation/advancedLogic.go
> +	}
объединила в логику шахов

2023-03-11 17:28 UTC, loskutovanl commented on validation/controllers_test.go
> +			t.Fatalf("unexpected reply: %s", res.Status)
добавила проверку на Head во все тесты (Simple, Advanced, FuzzSImple, FuzzAdvanced). Добавила проверку на наличие тела ответа

2023-03-11 17:47 UTC, loskutovanl commented on validation/advancedLogic.go
> +	}
Насколько я понимаю, ошибка может возникнуть при вызове board.Get(s) в тех случаях если функции, к которым обращается isSquareChecked где-то определяет клетку square, как число которое выходит за пределы 0-63.

Добавила в обработку ошибок

2023-03-11 17:49 UTC, loskutovanl commented
Внесла исправления в соответствии с замечаниями

2023-03-11 18:36 UTC, nekr0z commented on validation/advancedLogic.go
> +	}
> ошибка может возникнуть при вызове board.Get(s) в тех случаях если функции, к которым обращается isSquareChecked где-то определяет клетку square, как число которое выходит за пределы 0-63

Да, верно.
Но ведь ты это значение square получила через getSquareByPiece — разве она могла вернуть тебе клетку за пределами?

2023-03-11 18:40 UTC, loskutovanl commented on validation/advancedLogic.go
> +	}
я имею в виду, что в isSquareChecked через другие функции проверяются клетки, с которых могли шаховать кони/слоны/ферзи. Если я где-то косячу с определением клетки с которой мог быть шах и она выходит за рамки дозволенного, то board.Get(s) выдаст ошибку, когда я обращусь к нему с этой клеткой.
Клеткой не короля, которую определяем getSquareByPiece, а с клеткой, где находится предполагаемый соперник от которого ждем шах

2023-03-11 19:41 UTC, nekr0z commented on validation/advancedLogic.go
> +	}
Ага, понял. В любом случае это — признак косяка в коде, и превращается в Internal Server Error (кстати, фаззер должен на него наткнуться тогда ;)

2023-03-13 07:04 UTC, loskutovanl commented on validation/advancedLogic.go
> +	}
![IMG_20230313_100302.jpg](https://user-images.githubusercontent.com/108513445/224630437-56480856-4016-492d-8666-e0d5c0065cc5.jpg)

За 10 минут фаззер ошибку internal server error не нашел

2023-03-13 07:56 UTC, loskutovanl commented
Удалила свою логику по определению шахов, использовала логику @nekr0z  из position.ThreatsTo.
Столкнулась с проблемой при валидации рокировки. Когда проверяю, проходит ли король через битое поле - я проверяю на шах клетку, в которой нет фигуры.

Чтобы не плодить лишние сотни строк моих проверок,
Предлагаю добавить обработку этого непосредственно в position.ThreatsTo, например в таком виде:


func ThreatsTo(s board.Square, b board.Board, isW bool) []board.Square {
	if s < 0 || s > 63 {
		return nil
	}
	var isW, isB bool
	var out []board.Square
	if getPiece(b, s) != 0 {
		if getPiece(b, s)%2 == 0 {
			isB = true
isW = false
		} else {
			isW = true
		}
	} else {
if !isW {
isB = true
}
}

2023-03-13 08:43 UTC, nekr0z commented
> Чтобы не плодить лишние сотни строк моих проверок, Предлагаю добавить обработку этого непосредственно в position.ThreatsTo

У меня была эта мысль, но я решил, что проще будет у тебя в validation набросать что-то вроде:
```go
func squareUnderAttack(b board.Board, s board.Square, weAreWhite bool) bool {
    p := board.BlackPawn
    if weAreWhite {
        p = board.WhitePawn
    }
    err := b.Put(s, p)
    if err != nil {
        // кто-то пихает невалидный Square, да и хрен с ним
        return false
    }
    return len(position.ThreatsTo(s)) > 0
}
```
;-)

2023-03-13 12:49 UTC, nekr0z commented
> ```go
>     if err != nil {
>         // кто-то пихает невалидный Square, да и хрен с ним
>         return false
>     }
> ```

Это в реальности немножно не работает, потому что Put() выдаёт ошибку и в том случае, если клетка уже занята ;) Но в этом случае можно просто проверять об имеющуюся фигуру.

Сейчас будет PR :)

2023-03-13 14:33 UTC, nekr0z commented on validation/advancedLogic.go
> +	}
> фаззер ошибку internal server error не нашел

Я ж с этого и начал, что её не должно быть. :)

2023-03-13 14:34 UTC, nekr0z commented
@loskutovanl #40

2023-03-14 11:08 UTC, loskutovanl commented
ну вроде хорошо получилось :)
Надо что-то еще править?

КМК,
Вариант 1. Сливаем и радуемся.
Вариант 2. Я могу переделать все функции так, чтобы они работали с типом board.Square вместе локального square.
Но тогда я захочу расширять методы board.Square для своего удобства diffRow, diffColumn и т.п. наподобие того что у меня написано[вот здесь](https://github.com/sadmadrus/chessBox/blob/dev/validation/moves.go#:~:text=%7D-,//%20diffRow%20%D0%B4%D0%B0%D0%B5%D1%82%20%D1%80%D0%B0%D0%B7%D0%BD%D0%B8%D1%86%D1%83%20%D0%B2%20%D1%80%D1%8F%D0%B4%D0%B0%D1%85%20%D0%BC%D0%B5%D0%B6%D0%B4%D1%83%20%D0%BA%D0%BB%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8%20s1%20%D0%B8%20s2.,%7D,-//%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20move). 
Не странно будет, если такое приедет в пакет board?

2023-03-14 14:27 UTC, nekr0z commented
> Не странно будет, если такое приедет в пакет board?

Вопрос не в странности, вопрос в полезности.

Обычно из пакета стараются экспортировать только достаточный минимум типов/методов/констант, чтобы этим пакетом можно было пользоваться по назначению. В том числе и потому, что — при необходимости — будет проще написать замену или другую реализацию для пакета (или отдельного интерфейса), у которого три публичных метода, а не тридцать три.

В Go расширять импортированные типы новыми методами нельзя, и писать «обёртки» — вроде твоего square — нормальная практика. Мне нравится подход, при котором если конкретная обёртка нужна в одном пакете, она остаётся обёрткой, а если в двух-трёх пакетах оказываются востребованы одинаковые обёртки, нужные методы внедряются в исходный пакет (или пишется отдельный пакет с обёрткой).

2023-03-14 14:33 UTC, loskutovanl commented
> В Go расширять импортированные типы новыми методами нельзя, и писать «обёртки» — вроде твоего square — нормальная практика. Мне нравится подход, при котором если конкретная обёртка нужна в одном пакете, она остаётся обёрткой, а если в двух-трёх пакетах оказываются востребованы одинаковые обёртки, нужные методы внедряются в исходный пакет (или пишется отдельный пакет с обёрткой).

В таком случае оставляем как есть

2023-03-14 14:58 UTC, nekr0z requested changes
По-прежнему LGTM в целом, но докопаться-то надо!.. ;)

2023-03-14 14:58 UTC, nekr0z commented on validation/controllers_test.go
> +			}
Ты проверяешь, что на GET ответ с телом, но не проверяешь, что на HEAD ответ без тела :)

2023-03-14 14:58 UTC, nekr0z commented on validation/controllers_test.go
> +				}
Вот эта конструкция (здесь и далее) выглядит не очень опрятно. ИМХО, лучше было бы так:
```go
for _, method := range []string{"GET", "HEAD"} {
    client := &http.Client{}
    req, _ := http.NewRequest(method, u.String(), nil)
    res, err := client.Do(req)
<...>
}
```
Это немножко более громоздко в написании, но потом проще читать и поддерживать.

2023-03-15 10:56 UTC, loskutovanl commented on validation/controllers_test.go
> +				}
сделала так во всех 4 тестах. Также заодно добавила проверку на метод "POST"

2023-03-15 11:02 UTC, nekr0z approved these changes
Вроде годно…

2023-03-15 11:23 UTC, loskutovanl commented
смержила изменения dev сюда.

Мержим в дев?

2023-03-15 11:24 UTC, merged