Db description
sadmadrus/chessBox pull request #52
Opened 2023-03-30 18:35 UTC by loskutovanl

WIP

to-do, to-do, to-dooooo
- [ ]  общее описание сервиса
- [ ]  методы users
- [ ]  получение истории moves
- [ ]  как обыграть "отмену" хода

2023-03-31 20:39 UTC, nekr0z requested changes
Навскидку — вещи, которые сразу бросились в глаза. Потом надо будет ещё почитать-подумать…

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +
Для базы данных лучше использовать не этот ООПный пережиток, а [диаграмму соотношений](https://mermaid.js.org/syntax/entityRelationshipDiagram.html) — там и структуру таблиц набросать можно.

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +  * `400 Bad Request` - данные корректны, ошибка записи в БД
Некорректные данные — это Bad Request. Корректные данные, но неудавшаяся запись — это `5xx`.

`4xx` — это всегда ошибка запрашивающего: не туда, не про то, не так сформулирован, требует невозможного, прав не хватает, [до чайника докопался](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/418) и т.д. Если запрос корректен, это не `4xx`.

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +* password_hash
Параметры задаются в каком виде? URL query? Webform-URL-encoded? Вообще JSON?

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +* password_hash
И да, почему здесь сразу нельзя задать `profile_info`?

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +* profile_info
Если `username` уникально, то зачем нам отдельно ID? Надо заводить ключ по `username` тогда.

А если не уникально, тогда почему во всех запросах оно, а не ID?

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +class sessions {
Если я правильно понимаю, эта информация относится к _игре_, а не к игровой сессии? Тогда её надо так и назвать, чтобы не было путаницы.

Игра может откладываться многократно, и состоять из нескольких последовательных сессий. После окончания игры игровая сессия закончится, а игра (и запись о ней в БД) останется — в статусе «состоялась».

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +  int loss_count
Я, конечно, не эксперт в базах данных, но это выглядит, как раскладывание граблей.

У нас есть таблица с информацией об играх, там есть привязка исхода каждой игры к игрокам. Получить из неё количество побед, поражений и ничьих — это пара `SELECT`ов. Зачем дополнительно хранить эту информацию тут, рискуя, что она в один прекрасный момент «разойдётся» с информацией, вычисляемой из таблицы с играми, и придётся мучительно соображать, которой из таблиц следует верить?

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +  update_board_usfen()
FEN лучше читается, а строка с пробелами в любой приличной базе данных нормально сохранится. Есть причина использовать UsFEN тут?

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +  int user_id_black
Тут просится отдельная таблица, задающая соответствие пользователь-игра-цвет фигур (пользователь из таблицы с пользователями — многие ко многим; игра из таблицы с играми — многие к одному (вернее, два к одному, но технически на большинстве БД это «многие»); комбинация игра+цвет уникальна (т.е. не может быть двое игроков белыми в одной игре); надо ли делать уникальной комбинацию игрок+игра, или можно позволить игроку играть и белыми, и чёрными (т.е. самому с собой) — вопрос для обсуждения).

Это упростит потом выборку из БД многократно, если не на порядки.

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +// одна таблица для всей истории vs. отдельная таблица для каждой сессии ?
Одна для всех, разумеется. Отдельная таблица под каждую игру — это вообще не про реляционные базы данных, и масштабировать это почти невозможно потом.

А вот как трактовать расхождение между таблицей ходов и полем «позиция на доске» из таблицы игр — это надо продумать заранее. В том, что такое расхождение возникнет, можно ни секунды не сомневаться, коль скоро допускается запись отдельно ходов и отдельно позиции — даже если мы будем _очень_ стараться, и всю логику напишем идеально, останутся «гонки» — у нас ведь микросервисы:

Записали ход, запись прошла. Послали позицию, сеть прилегла, запрос не долетел. Пока сеть не восстановилась, пока запрос не продублировали, другой агент дёрнул базу данных по этой игре — а вот и расхождение!

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +// TODO: подумать, как обыграть отмену ходов.
Так, как это делают на FICS и lichess: прописывать вариацию. В этой таблице нужно поле, которое будет указывать на номер ветки, и по умолчанию ставить `0` — «основная ветка». При отмене всю пачку отменённых ходов объявлять новой вариацией, обновлять на них номер вариации, а «основную» ветку вести дальше по игре.

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
Время таки не пишем?

2023-03-31 20:39 UTC, nekr0z commented on docs/database.md
> +| -------- | --------------------| ------------------|----------------------|----------------------| ----------------------|------------------|--------------|--------|
Время?

2023-04-04 08:45 UTC, sadmadrus commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
мне кажется без времени будет много проблем в дальнейшем. Сформулировать мысль не могу пока четко, но чую прям

2023-04-08 08:38 UTC, loskutovanl commented on docs/database.md
> +  * `400 Bad Request` - данные корректны, ошибка записи в БД
исправила

2023-04-08 08:39 UTC, loskutovanl commented on docs/database.md
> +  update_board_usfen()
нет, исправила

2023-04-11 11:06 UTC, loskutovanl commented on docs/database.md
> +class sessions {
переименовала таблицу в games.

Получается нужна еще таблица где ставится в соответствие игра игровым сессиям?

2023-04-11 11:06 UTC, loskutovanl commented on docs/database.md
> +* profile_info
makes sense, сделала UK username

2023-04-11 11:08 UTC, loskutovanl commented on docs/database.md
> +* password_hash
> Параметры задаются в каком виде? URL query? Webform-URL-encoded? Вообще JSON?

Насколько понимаю, у нас нет ограничений и можно задать в любом виде, просто договориться в каком



> И да, почему здесь сразу нельзя задать `profile_info`?

добавила

2023-04-11 11:09 UTC, loskutovanl commented on docs/database.md
> +  int user_id_black
сделала

2023-04-11 11:09 UTC, nekr0z commented on docs/database.md
> +class sessions {
> Получается нужна еще таблица где ставится в соответствие игра игровым сессиям?

Не знаю, надо ли. Пока у нас по тем архитектурным документам, которые есть, сессии вроде как не пишутся в базу; вполне возможно, что это соответствие будет держать в памяти менеджер сессий…

2023-04-11 11:11 UTC, loskutovanl commented on docs/database.md
> +// одна таблица для всей истории vs. отдельная таблица для каждой сессии ?
> А вот как трактовать расхождение между таблицей ходов и полем «позиция на доске» из таблицы игр — это надо продумать заранее. В том, что такое расхождение возникнет, можно ни секунды не сомневаться, коль скоро допускается запись отдельно ходов и отдельно позиции — даже если мы будем _очень_ стараться, и всю логику напишем идеально, останутся «гонки» — у нас ведь микросервисы:

могу предположить, что при наличии поля updated_at в обеих таблицах, при расхождении нас будет интересовать более свежий updated_at

2023-04-11 11:12 UTC, nekr0z commented on docs/database.md
> +* password_hash
> Насколько понимаю, у нас нет ограничений и можно задать в любом виде, просто договориться в каком

Именно, и договариваться надо как раз вот прямо здесь :)

2023-04-11 11:20 UTC, loskutovanl commented on docs/database.md
> +// TODO: подумать, как обыграть отмену ходов.
добавила ветку

2023-04-11 11:20 UTC, nekr0z commented on docs/database.md
> +// одна таблица для всей истории vs. отдельная таблица для каждой сессии ?
> при расхождении нас будет интересовать более свежий updated_at

Наверно, это рабочий вариант. Тогда надо прописывать это поведение, и, наверно, прописать, что за updated_at следит сам сервис БД, и это его внутреннее служебное поле для разрешения гонок? Или это очевидно, и можно не писать?

2023-04-11 11:20 UTC, loskutovanl commented on docs/database.md
> +| -------- | --------------------| ------------------|----------------------|----------------------| ----------------------|------------------|--------------|--------|
не могу сообразить, какое время мы хотим записать?

2023-04-11 11:21 UTC, loskutovanl commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
Правильно понимаю, что мы хотим записать start_time и end_time, а не продолжительность?

2023-04-11 11:28 UTC, loskutovanl commented on docs/database.md
> +// одна таблица для всей истории vs. отдельная таблица для каждой сессии ?
добавила в первую секцию в примечание

2023-04-11 11:28 UTC, nekr0z requested changes

2023-04-11 11:28 UTC, nekr0z commented on docs/database.md
> +  GAMES2USERS ||--|{ GAMES : places
Тут для каждой записи в GAMES будет ровно две записи в GAMES2USERS (про белых и про чёрных), а нарисовано будто наоборот. Надо `}|--||`.

(По-хорошему, надо бы `}--||` — потому что не может не быть второй записи про игру — но mermaid так, кажется, пока не умеет.)

2023-04-11 11:28 UTC, nekr0z commented on docs/database.md
> +     string color "white, black allowed"
Думаешь, boolean не обойдёмся?..

Хотя как знать, конечно…

2023-04-11 11:30 UTC, loskutovanl commented on docs/database.md
> +* password_hash
указала  Webform-URL-encoded в первом общем разделе документа

Если кто не согласен - говорите

2023-04-11 11:31 UTC, nekr0z commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
Для хода достаточно затраченного времени, как мне кажется.

2023-04-11 11:32 UTC, nekr0z commented on docs/database.md
> +| -------- | --------------------| ------------------|----------------------|----------------------| ----------------------|------------------|--------------|--------|
Тут, как минимум, нужны данные о контроле времени в игре (считаем/не считаем, какие лимиты), плюс, наверно, часы каждого игрока на старте или на финише (если, допустим, гандикап давался).

2023-04-11 11:44 UTC, nekr0z commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
HTTP 403 — это «forbidden», а не «bad request» (тут и далее).

По-хорошему, тут надо или 400 (bad request), или отдавать информацию о том, что именно не так. Например, если email кривой — это да, это 403. А вот если, например, пользователь уже существует — это 409 (conflict)...

2023-04-11 11:45 UTC, nekr0z commented on docs/database.md
> +  * `400 Bad Request` - данные корректны, ошибка доступа к БД
Тут забыла на 500 заменить.

2023-04-11 11:46 UTC, nekr0z commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
Не могу себе представить, какой запрос здесь должен давать forbidden в ответ…

2023-04-11 19:13 UTC, sadmadrus commented on docs/database.md
> +* password_hash
> Параметры задаются в каком виде? URL query? Webform-URL-encoded? Вообще JSON?

Предлагаю пользовать json как самый понятный вариант и простой для отладки

2023-04-11 19:16 UTC, sadmadrus commented on docs/database.md
> +class sessions {
Тут надо хорошо подумать, что бы таблицы привести к нормальному виду. Игровая сессия не равно игра. Вопрос в том, а стоит ли хранить саму сессию после окончания? Вероятно она лишняя

2023-04-11 19:19 UTC, sadmadrus commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
Мы пишем обязательно временную метку для записи по серверному времени. Для хода тогда пишем продолжительность. Если надо - посчитаем остальное

2023-04-11 19:21 UTC, sadmadrus commented on docs/database.md
> +| -------- | --------------------| ------------------|----------------------|----------------------| ----------------------|------------------|--------------|--------|
А, вы про время внутри игры... Таймеры игроков и продолжительность ходов?

2023-04-11 19:23 UTC, nekr0z commented on docs/database.md
> +class sessions {
После окончания точно не надо :)

2023-04-11 19:27 UTC, nekr0z commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
> по серверному времени

Это ты сейчас мощно задвинул!

У нас гейт, игровая сессия и сервис БД — это три разных микросервиса, которые могут жить на трёх разных серверах (и иметь несовпадающие часы). Что считать «серверным» временем?

2023-04-11 19:29 UTC, nekr0z commented on docs/database.md
> +  USERS ||--|{ GAMES2USERS : places
А тут по-хорошему надо `|o--|{` — может же существовать юзер, не участвовавший (пока) ни в одной игре.

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +    string email "example@example.example is allowed"
А мы прям будем адреса емейлов хранить? Их же тогда надо валидировать будет, а это [сложно](https://www.netmeister.org/blog/email.html)!

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +  * id пользователя
У нас теперь нет id :)))

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
Некорректны в каком смысле? Нет такого пользователя? Это 404 (not found).

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +  * `403 Forbidden` - данные некорректны, поэтому не извлечены из БД
В каком смысле 403? Если `username` существует, его надо извлекать, или рисовать 500 (или 503, или 502, или что там случилось — если уж мы про подробности). А если не существует, это 404.

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +  * created_at, profile_info, email
Надеюсь, здесь и везде, где мы будем совать в JSON время, мы будем делать это в ISO 8601, и непременно в UTC? Может, прописать это в явном виде — на всякий пожарный?

А точность — до минут? До секунд? До миллисекунд? Надо ли прописать?

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +* запись о новой игре в таблице games. Автоматически выставляется время created_at, updated_at, winner=None, white_turn=true, is_active=true.
То есть мы точно, гарантированно, никогда не планируем поддерживать ситуацию «начали играть за доской, не доиграли, решили продолжить в chessBox»?

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +* user_id_black
id?

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
Ок, могу: user_white == user_black.

Или всё-таки можно самому с собой играть, м?

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
Тут, опять таки, либо просто 400 на всё, либо надо разделять:
- нет такой игры — это 404,
- кривой JSON, или в нём кривой FEN — это 400 (если сервис БД валидирует FEN при записи, кстати — а он да?)
- outcome == 8 — это либо 400, либо 403, тут уж как представить,
- новый outcome для игры, у которой он уже ненулевой — это 409.

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +  * []id
Мне кажется немного стрёмным делать это так. Представь ситуацию, когда менеджер сессий посылает такой запрос, но сеть отваливается прежде, чем он получит ответ: база игры уже перевела в неактивное состояние, но менеджер сессий никогда не узнает, какие именно…

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не извлечены в БД
Кривой JSON — 400. Несуществующий id — 404.

403 здесь по логике вообще никак не может быть.

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +  * board_fen
Настройки тайминга, если мы их храним, тоже отдавать надо.

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +     int user_id FK "many-to-many"
В каком смысле "many-to-many"? Один ход может относиться к разным играм?

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +  GAMES ||--|{ MOVES : contains
Если возможна игра, в которой (пока) нет ходов (но, к примеру, уже есть id и игроки, поэтому мы её записали), то надо `||--o{` («one to zero-or-more»).

2023-04-11 20:17 UTC, nekr0z commented on docs/database.md
> +    int id PK
Вот конкретно тут руки чешутся зарядить-таки BIGINT, но, может быть, это и не надо…

2023-04-11 20:23 UTC, nekr0z commented on docs/database.md
> +  USERS ||--|{ GAMES2USERS : places
И да, вот это "places" надо или заменить на что-то, объясняющее связь (например, `"participate as black or white"`), или вообще убрать, чтоб не отвлекало (тут и ниже) — просто `""`.

2023-04-11 20:29 UTC, nekr0z commented on docs/database.md
> +  USERS ||--|{ GAMES2USERS : places
[mermaid.live](https://mermaid.live) — нормальная вещь, можно пользоваться ;)

2023-04-12 10:10 UTC, loskutovanl commented on docs/database.md
> +* password_hash
> Предлагаю пользовать json как самый понятный вариант и простой для отладки

ок

2023-04-12 10:15 UTC, loskutovanl commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
> достаточно затраченного времени

> Для хода тогда пишем продолжительность

насколько я понимаю, в SQL нет типа времени, аналогичного time.Duration. Мы хотим записать продолжительность в формате int как количество чего-то (секунд, милисекунд...)?

2023-04-12 10:20 UTC, sadmadrus commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
а смысл в игре самому с собой?

2023-04-12 10:21 UTC, sadmadrus commented on docs/database.md
> +    string email "example@example.example is allowed"
предлагаю не связываться с почтами. Тут много подводных камней кроме валидации. Тут еще и юридическая составляющая может быть. Утекут адреса с именами пользователей - влепят по шапке

2023-04-12 10:26 UTC, sadmadrus commented on docs/database.md
> +  * created_at, profile_info, email
все эти временные заморочки меня ставят в ступор. Хотелось все метки делать в формате UnixTime, но тут предлагаю обсудить

2023-04-12 10:29 UTC, sadmadrus commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
> > по серверному времени
> 
> Это ты сейчас мощно задвинул!
> 
> У нас гейт, игровая сессия и сервис БД — это три разных микросервиса, которые могут жить на трёх разных серверах (и иметь несовпадающие часы). Что считать «серверным» временем?

чьерт побьери! никак не привыкну к микросервисам :) нужен механизм синхронизации. Или отдать на откуп сервису БД определение времени, но тогда есть сложности с отборами по временным меткам

2023-04-12 10:30 UTC, loskutovanl commented on docs/database.md
> +    string email "example@example.example is allowed"
будет какая-то авторизация... через что можно авторизоваться кроме телефона и имейла?
лично я забываю все никнеймы на вторые сутки, если где-то регистрируюсь не через почту/телефон :(

2023-04-12 10:33 UTC, loskutovanl commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
* `400 Bad Request` - profile_info и/или email некорректны, поэтому не записаны в БД
  * `404 Not Found` - пользователь с указанным username не найден

2023-04-12 10:34 UTC, loskutovanl commented on docs/database.md
> +  * `403 Forbidden` - данные некорректны, поэтому не извлечены из БД
ты прав, исправила

2023-04-12 10:40 UTC, loskutovanl commented on docs/database.md
> +  * created_at, profile_info, email
в первом абзаце добавила:
Ответы возвращаются в виде JSON (время: ISO 8601, UTC с точностью до миллисекунд).

если тайминг ходов может быть 3|3 то есть оперируем секундами, кажется для точности нужны миллисекунды. Имеет смысл тогда все единообразно делать до миллисекунд или поля created_at\updated_at можно сделать менее точными?

2023-04-12 10:50 UTC, loskutovanl commented on docs/database.md
> +     int user_id FK "many-to-many"
1 пользователь может участвовать в разных играх? Это же про games?

2023-04-12 10:55 UTC, loskutovanl commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
типа поразмыслить на несколько ходов вперед в конкретной позиции - я понимаю. а играть с собой всю игру - тоже не понимаю

2023-04-12 10:59 UTC, loskutovanl commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
сделала с детализацией

2023-04-12 10:59 UTC, loskutovanl commented on docs/database.md
> +  * []id
А как надо?

2023-04-12 11:01 UTC, loskutovanl commented on docs/database.md
> +  * board_fen
добавила

2023-04-12 11:14 UTC, nekr0z commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
> а смысл в игре самому с собой?

Нет так нет :)

2023-04-12 11:15 UTC, nekr0z commented on docs/database.md
> +    string email "example@example.example is allowed"
> будет какая-то авторизация... через что можно авторизоваться кроме телефона и имейла? лично я забываю все никнеймы на вторые сутки, если где-то регистрируюсь не через почту/телефон :(

Ты всегда можешь использовать мейл как никнейм ;)

2023-04-12 11:17 UTC, nekr0z commented on docs/database.md
> +  * created_at, profile_info, email
> если тайминг ходов может быть 3|3 то есть оперируем секундами, кажется для точности нужны миллисекунды. Имеет смысл тогда все единообразно делать до миллисекунд или поля created_at\updated_at можно сделать менее точными?

Можно за единообразием не гнаться, КМК, главное задокументировать, что и где.

2023-04-12 11:19 UTC, nekr0z commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
> чьерт побьери! никак не привыкну к микросервисам :) нужен механизм синхронизации. Или отдать на откуп сервису БД определение времени, но тогда есть сложности с отборами по временным меткам

Есть мысль, что внутренними метками должен заниматься сервис БД, ему и карты в руки, а всё, что связано с ходами, может фиксироваться по времени гейта — его мы контролируем, в его честности уверены, и это позволит игнорировать задержки внутри системы.

2023-04-12 11:23 UTC, nekr0z commented on docs/database.md
> +     int user_id FK "many-to-many"
Извини, не к той строчке коммент написал. Но в MOVES для game_id написано-таки many-to-many :)

2023-04-12 11:25 UTC, nekr0z commented on docs/database.md
> +  * []id
Честно говоря, не знаю, надо думать.

Мне в голову приходит сделать возможность отдельно запросить id всех игр, соответствующих критерию, и отдельно возможность изменить статус пачке игр (причём по списку явно переданных id)

2023-04-12 11:27 UTC, nekr0z commented
А вот ещё у нас тут в нескольких местах для GET прописан входящий параметр — он как передаётся? Чай, у GET'а тела быть не может…

2023-04-13 16:40 UTC, sadmadrus commented on docs/database.md
> +    string email "example@example.example is allowed"
можно попробовать подобрать что-то типа хэша для хранения почты как логина, но все равно эта идея меня не радует. Не хочется связываться с тем, в чем вообще нет компетенций и за что можно получить по шапке от дяди майора

2023-04-13 16:41 UTC, sadmadrus commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
получается, что нужно будет тянуть метки времени сквозь сервисы от гейта - не удобно

2023-04-13 19:18 UTC, nekr0z commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
> получается, что нужно будет тянуть метки времени сквозь сервисы от гейта - не удобно

Тянуть-то максимум от гейта до сессии, никто другой тут не участвует, а решение по времени (уложилась ли продолжительность хода в лимит, или флаг упал) принимать будет именно сессия; она может сделать это и на основании информации, полученной от гейта (две метки времени: время, когда игрок получил информацию о ходе соперника и время, когда игрок сделал свой ход).

Там придётся добавить логику на случай падения сети между гейтом и сессией, но я себе эту схему уже примерно представляю, ничего сложного.

Просто хочется метки времени фиксировать максимально «близко» к игроку — просто из соображений гуманности. Ему и так сетевой лаг между собой и гейтом терпеть… ;)

2023-04-13 19:23 UTC, nekr0z commented on docs/database.md
> +// TODO: подумать, как обыграть отмену ходов.
Выходит, сервис БД у нас самостоятельно отслеживает ветки и занимается их нумерованием? Это немножко против принципа разделения ответственности…

Опять таки, тогда надо прописывать тут же, в сервисе БД, логику проверки уникальности ветки. А то возможна ситуация, когда игроки, откатываясь до, условно говоря, 25-го хода, попеременно разыгрывают одну из двух вариаций по десятку ходов каждая — восемьсот раз. :-D Сохранять в БД все 800 вариаций, при том что реально их там две, а то и вовсе одна, кажется неправильным…

2023-04-13 19:27 UTC, nekr0z commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
> в формате int как количество чего-то (секунд, милисекунд...)?

Можно даже в bigint, не жалко. Пусть миллисекунды. В любом случае, надо, чтобы эта конверсия была на стороне сервиса БД. Чтобы он принимал продолжительность отрезка времени в ISO8601, и отдавал её же, а уж как там он её хранит — в int, в bigint, да хоть как string — это его дело.

2023-04-13 19:37 UTC, nekr0z commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
Тогда надо писать, что корректно (и что некорректно) в качестве profile_info. И — свят-свят — валидировать email. :)))

2023-04-13 19:44 UTC, nekr0z commented on docs/database.md
> +  * created_at, profile_info, email
> все эти временные заморочки меня ставят в ступор. Хотелось все метки делать в формате UnixTime, но тут предлагаю обсудить

UnixTime — это [боль](https://www.netmeister.org/blog/epoch.html), потому что каждая високосная секунда вызывает дыру в непрерывности, и это надо отдельно обрабатывать; ну его нафиг. Время и без этого — [сложная штука](https://gist.github.com/timvisee/fcda9bbdff88d45cc9061606b4b923ca#file-falsehoods-programming-time-list-md)

2023-04-15 10:36 UTC, loskutovanl commented on docs/database.md
> +// TODO: подумать, как обыграть отмену ходов.
согласна про разделение ответственности. поменяла так что branch это входящий параметр при запросе.
Сделала новый метод, чтобы получать массив всех ходов следующих после указанного move_id (чтобы при методе отмены знать кому выставлять новый номер ветки)

2023-04-15 10:42 UTC, loskutovanl commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
в таблице moves было:
`    datetime start_time
    datetime end_time`

стало:
`    int duration "in milliseconds"`

2023-04-15 10:44 UTC, loskutovanl commented on docs/database.md
> +| -------- | --------------------| ------------------|----------------------|----------------------| ----------------------|------------------|--------------|--------|
`    string timing "формат времени для игры (Null — игра без учёта времени)"
    time time_white
    time time_black`
?

2023-04-15 10:47 UTC, loskutovanl commented on docs/database.md
> +  GAMES2USERS ||--|{ GAMES : places
исправила

2023-04-15 10:48 UTC, loskutovanl commented on docs/database.md
> +     string color "white, black allowed"
наверное шахмат втроем не будет

2023-04-15 10:50 UTC, loskutovanl commented on docs/database.md
> +  USERS ||--|{ GAMES2USERS : places
исправила

2023-04-15 10:52 UTC, loskutovanl commented on docs/database.md
> +    string email "example@example.example is allowed"
email убрала, оставила только username

2023-04-15 10:53 UTC, loskutovanl commented on docs/database.md
> +  * `403 Bad Request` - данные некорректны, поэтому не записаны в БД
email убрали, `400` убрали

2023-04-15 11:04 UTC, loskutovanl commented on docs/database.md
> +* запись о новой игре в таблице games. Автоматически выставляется время created_at, updated_at, winner=None, white_turn=true, is_active=true.
добавила white_turn и board_fen во входящие параметры. тогда можно с любой точки начинать игру

2023-04-15 11:06 UTC, loskutovanl commented on docs/database.md
> +     int user_id FK "many-to-many"
исправила

2023-04-15 11:14 UTC, loskutovanl commented on docs/database.md
> +    int id PK
Давайте подумаем.

в каждой игре в среднем 40 ходов.
1,250,000 партий играется на чес ком каждый день.
будь мы чес ком, int нам бы хватило на 43 дня, а bigint - на 184,467,440,737 дней (то есть 505 миллионов лет).
Ставим bigint?

2023-04-15 11:21 UTC, loskutovanl commented
> А вот ещё у нас тут в нескольких местах для GET прописан входящий параметр — он как передаётся? Чай, у GET'а тела быть не может…

для GET передавать в url, для всех остальных в json?

2023-04-15 11:24 UTC, loskutovanl commented on docs/database.md
> +  * []id
Это ничего, что мы искусственно удлиняем операцию в два раза?

2023-04-16 11:41 UTC, nekr0z commented on docs/database.md
> +* запись о новой игре в таблице games. Автоматически выставляется время created_at, updated_at, winner=None, white_turn=true, is_active=true.
white_turn разве не лишнее? В FEN же содержатся эти данные.

2023-04-21 06:01 UTC, sadmadrus commented on docs/database.md
> +| -------- |--------------------| ------------------|---------------|
ОК. поддерживаю такое решение

2023-04-21 06:03 UTC, sadmadrus commented on docs/database.md
> +  * created_at, profile_info, email
> > все эти временные заморочки меня ставят в ступор. Хотелось все метки делать в формате UnixTime, но тут предлагаю обсудить
> 
> UnixTime — это [боль](https://www.netmeister.org/blog/epoch.html), потому что каждая високосная секунда вызывает дыру в непрерывности, и это надо отдельно обрабатывать; ну его нафиг. Время и без этого — [сложная штука](https://gist.github.com/timvisee/fcda9bbdff88d45cc9061606b4b923ca#file-falsehoods-programming-time-list-md)...

ок. Доверюсь твоему опыту :)

2023-04-21 06:04 UTC, sadmadrus commented on docs/database.md
> +    int id PK
ставь и забудь :100:

2023-04-25 07:25 UTC, DinaTamieva commented on docs/database.md
> +  * `403 Forbidden` - данные некорректны, поэтому не извлечены из БД
403 Forbidden | Означает, что клиент не обладает достаточными правами доступа к запрошенному ресурсу. Также данный код можно встретить, если сервер обнаружил вредоносные данные, отправленные клиентом в запросе.

Некорректные данные тогда уж:
400 Bad Request | Данный код можно увидеть, если запрос был сформирован с ошибками. Например, в нем отсутствовали символы завершения строки.



<!--EndFragment-->
</body>
</html>


<!--EndFragment-->
</body>
</html>

2023-04-25 10:52 UTC, nekr0z commented on docs/database.md
> +  * `403 Forbidden` - данные некорректны, поэтому не извлечены из БД
@DinaTamieva в актуальной версии пулл-реквеста это место уже исправлено (на что намекает плашка «outdated»), повторно на это указывать ни к чему — это только создаёт лишнюю когнитивную нагрузку на всех, кому прилетело уведомление о комментарии.

2023-05-07 07:48 UTC, loskutovanl commented on docs/database.md
> +    int id PK
ok, bigint

2023-05-07 07:53 UTC, loskutovanl commented
Все предыдущие комментарии учла. Дайте знать, что пропустила, или новые вопросы, если есть

2023-06-05 13:18 UTC, loskutovanl commented
Добрый день. За неимением новых комментариев и пожеланий предлагаю смержить. @sadmadrus 

Если есть возражения - озвучивайте.

2023-06-05 13:25 UTC, merged